# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        run: |
          touch .env
          echo "REACT_APP_API_KEY= ${{ secrets.REACT_APP_API_KEY }}" >> .env
          echo "REACT_APP_AUTH_DOMAIN= ${{ secrets.REACT_APP_AUTH_DOMAIN }}" >> .env
          echo "REACT_APP_PROJECT_ID= ${{ secrets.REACT_APP_PROJECT_ID }}" >> .env
          echo "REACT_APP_STORAGE_BUCKET= ${{ secrets.REACT_APP_STORAGE_BUCKET }}" >> .env
          echo "REACT_APP_MESSAGING_SENDER_ID= ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}" >> .env
          echo "REACT_APP_APP_ID= ${{ secrets.REACT_APP_APP_ID }}" >> .env
          echo "REACT_APP_MEASUREMENT_ID= ${{ secrets.REACT_APP_MEASUREMENT_ID }}" >> .env
      - run: npm i --force
      - run: CI=false npm run build


      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./build/
          remote_path: /var/www/my-app/
          remote_host: ec2-52-220-116-235.ap-southeast-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.MY_SECRET }}"
